---
kind: pipeline
type: docker
name: testing

steps:
- name: testing
  image: geekycode/python-generic
  environment:
    GITEA_PAT:
      from_secret: gitea_pat
  commands:
  - ./success.py

image_pull_secrets:
- dockerconfig
